USE 18_assign2db;
DROP VIEW IF EXISTS PASSENGERS;
DROP VIEW IF EXISTS PASSENGERS1;

CREATE VIEW PASSENGERS AS SELECT PASSENGER.FIRST_NAME, PASSENGER.LAST_NAME, TRIP.TRIP_NAME, TRIP.COUNTRY_VISITED, TOOK.PRICE  FROM PASSENGER, TRIP, TOOK WHERE (PASSENGER.ID=TOOK.PASSENGER_ID AND TRIP.ID=TOOK.TRIP_ID);
SELECT * FROM PASSENGERS;

CREATE VIEW PASSENGERS1 AS SELECT PASSENGER.FIRST_NAME, PASSENGER.LAST_NAME, TRIP.TRIP_NAME, TRIP.COUNTRY_VISITED, TOOK.PRICE FROM PASSENGER, TRIP, TOOK WHERE(PASSENGER.ID=TOOK.PASSENGER_ID AND TRIP.ID=TOOK.TRIP_ID AND TRIP.TRIP_NAME LIKE "%Castles%") ORDER BY TOOK.PRICE ASC;
SELECT * FROM PASSENGERS1;

SELECT * FROM BUS;
DELETE FROM BUS WHERE (BUS.LICENSE_PLATE_NUMBER LIKE "%UWO%");
SELECT * FROM BUS;

SELECT * FROM PASSENGER;
SELECT * FROM PASSPORT;
DELETE FROM PASSPORT WHERE(PASSPORT.COUNTRY_OF_CITIZENSHIP="Canada");
SELECT * FROM PASSPORT;
SELECT * FROM PASSENGER;
-- RECORDS IN PASSENGER IS NOT DELTED BECAUSE IT IS THE PARENT OF THE RECORD IN PASSPORT, AND DELETE CASCADE DELETES CHILD WHEN PARENT IS DELETED BUT NOT THE OTHER WAY AROUND

SELECT * FROM TRIP;
DELETE FROM TRIP WHERE TRIP_NAME = "California Wines";
SELECT * FROM TRIP;

DELETE FROM TRIP WHERE TRIP_NAME = "Arrivaderci Roma";
SELECT * FROM TRIP;
-- THE TRIP CANNOT BE DELETED BECAUSE IT IS A FOREIGN KEY IN OTHER TABLES AND THERE IS NO DELETE CASCADE ON IT

SELECT * FROM PASSENGER;
DELETE FROM PASSENGER WHERE FIRST_NAME = "Pam";
SELECT * FROM PASSENGER;
SELECT * FROM PASSENGERS;
DELETE FROM PASSENGER WHERE LAST_NAME = "Simpson";
SELECT * FROM PASSENGERS;
