SHOW DATABASES;
DROP DATABASE IF EXISTS 18_assign2db;
CREATE DATABASE 18_assign2db;
USE 18_assign2db;
SHOW TABLES;

CREATE TABLE IF NOT EXISTS BUS(LICENSE_PLATE_NUMBER VARCHAR(7), CAPACITY INT NOT NULL,PRIMARY KEY(LICENSE_PLATE_NUMBER));
CREATE TABLE IF NOT EXISTS TRIP(ID INT, START_DATE DATE NOT NULL, END_DATE DATE NOT NULL, COUNTRY_VISITED VARCHAR(30) NOT NULL,TRIP_NAME VARCHAR(50)NOT NULL, BUS_USED VARCHAR(7),PRIMARY KEY (ID), FOREIGN KEY(BUS_USED) REFERENCES BUS(LICENSE_PLATE_NUMBER) );
CREATE TABLE IF NOT EXISTS PASSENGER(ID INT, FIRST_NAME VARCHAR(20) NOT NULL, LAST_NAME VARCHAR(20) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS PASSPORT(PASSPORT_NUMBER VARCHAR(4), EXPIRY_DATE DATE NOT NULL, COUNTRY_OF_CITIZENSHIP VARCHAR(30) NOT NULL, BIRTH_DATE DATE NOT NULL, PASSENGER_ID INT, PRIMARY KEY(PASSPORT_NUMBER), FOREIGN KEY(PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS TOOK (PASSENGER_ID INT, TRIP_ID INT, PRICE FLOAT NOT NULL, PRIMARY KEY(PASSENGER_ID, TRIP_ID), FOREIGN KEY(PASSENGER_ID)REFERENCES PASSENGER(ID) ON DELETE CASCADE, FOREIGN KEY(TRIP_ID) REFERENCES TRIP(ID));

SHOW TABLES;
DESCRIBE TRIP; 
DESCRIBE PASSPORT;
DESCRIBE PASSENGER;
DESCRIBE TOOK;
