USE 18_assign2db;

-- Show trip names of all trips from Italy
SELECT TRIP_NAME FROM TRIP WHERE COUNTRY_VISITED="Italy";
-- Show the last names of all passengers with no repeats
SELECT LAST_NAME FROM PASSENGER GROUP BY LAST_NAME;
-- Show all the data in the bus table in the order of ascending trip name
SELECT * FROM TRIP ORDER BY TRIP_NAME ASC;
-- Show trip name, country visited and start date of trips starts later than April 30th, 2022
SELECT TRIP_NAME , COUNTRY_VISITED, START_DATE FROM TRIP WHERE START_DATE > "2022-04-30";
-- Show all travellers' first name, last name and birthday holding American passport
SELECT PASSENGER.FIRST_NAME, PASSENGER.LAST_NAME, PASSPORT.BIRTH_DATE FROM PASSENGER, PASSPORT WHERE (PASSPORT.PASSENGER_ID=PASSENGER.ID AND PASSPORT.COUNTRY_OF_CITIZENSHIP="USA");
-- Show all trips' names and capacity for trips starting between April 1st to Sept. 1st in 2022
SELECT TRIP.TRIP_NAME, BUS.CAPACITY FROM TRIP,BUS WHERE(TRIP.START_DATE>="2022-04-01" AND TRIP.START_DATE<="2022-09-01" AND TRIP.BUS_USED=BUS.LICENSE_PLATE_NUMBER);
-- Show information of passport which will expire in a year or has expired in a year and information about owners of these passports
SELECT PASSPORT.*, PASSENGER.* FROM PASSPORT, PASSENGER WHERE(PASSENGER.ID=PASSPORT.PASSENGER_ID AND (PASSPORT.EXPIRY_DATE < (SELECT ADDDATE(CURDATE(), INTERVAL 1 YEAR))));
-- List first and last name of travellers with last name starting with "S" and names of the trip they had or will have
SELECT PASSENGER.FIRST_NAME, PASSENGER.LAST_NAME, TRIP.TRIP_NAME FROM TOOK, PASSENGER, TRIP WHERE(TOOK.PASSENGER_ID=PASSENGER.ID AND TOOK.TRIP_ID=TRIP.ID AND PASSENGER.LAST_NAME LIKE "S%");
-- List total number of passengers and the trip name and trip id
SELECT TRIP.ID, TRIP.TRIP_NAME, COUNT(TOOK.PASSENGER_ID) AS NUMBER_OF_PASSENGERS FROM TOOK, TRIP WHERE (TOOK.TRIP_ID=TRIP.ID AND TRIP.TRIP_NAME="Castles of Germany");
-- List countries having trips and total amount of dollars brought for each country
SELECT TRIP.COUNTRY_VISITED, ROUND(SUM(TOOK.PRICE), 2) FROM TOOK, TRIP WHERE (TRIP.ID=TOOK.TRIP_ID) GROUP BY TRIP.COUNTRY_VISITED;
-- List passenger's last name, country of citizens, trip name and trip country name for passengers who travelled abroad
SELECT PASSENGER.LAST_NAME, PASSPORT.COUNTRY_OF_CITIZENSHIP, TRIP.TRIP_NAME, TRIP.COUNTRY_VISITED FROM PASSENGER, PASSPORT, TRIP, TOOK WHERE (PASSENGER.ID=PASSPORT.PASSENGER_ID AND TOOK.PASSENGER_ID=PASSENGER.ID AND TOOK.TRIP_ID=TRIP.ID AND PASSPORT.COUNTRY_OF_CITIZENSHIP != TRIP.COUNTRY_VISITED);
-- list bus trip id and names of bus trips not taken by any passengers
SELECT TRIP.ID, TRIP.TRIP_NAME FROM TRIP WHERE(SELECT EXISTS(SELECT * FROM TOOK WHERE TOOK.TRIP_ID=TRIP.ID)=FALSE);
-- SELECT THE PASSENGER PAYING THE MOST AMOUNT OF MONEY
SELECT MAX(TOTAL) AS "TOTAL_SPENT", PASSENGER.FIRST_NAME, PASSENGER.LAST_NAME, PASSPORT.COUNTRY_OF_CITIZENSHIP FROM (SELECT SUM(TOOK.PRICE) AS "TOTAL" FROM TOOK, PASSENGER WHERE(TOOK.PASSENGER_ID=PASSENGER.ID) GROUP BY PASSENGER.ID) AS TMP, PASSENGER, PASSPORT WHERE (PASSENGER.ID=PASSPORT.PASSENGER_ID);
-- FIND LIST OF THE TRIP HAVING LESS THAN 4 PEOPLE MAKING THEM
SELECT TRIP.TRIP_NAME, COUNT(PASSENGER_ID) AS "PEOPLE" FROM TOOK INNER JOIN TRIP ON TRIP.ID=TOOK.TRIP_ID GROUP BY TRIP_ID HAVING PEOPLE <4; 
-- display information of all buses
SELECT TRIP.TRIP_NAME AS "Bus Trip Name", COUNT(TOOK.PASSENGER_ID) AS "Current Number of Passengers", BUS.LICENSE_PLATE_NUMBER AS "Current Bus Assigned LICENSE Plate", BUS.CAPACITY AS "Capacity of Asiigned Bus" FROM TOOK INNER JOIN TRIP ON TRIP.ID=TOOK.TRIP_ID INNER JOIN  BUS ON TRIP.BUS_USED=BUS.LICENSE_PLATE_NUMBER GROUP BY TRIP_ID;
